language: csharp
dotnet: 5.0.100
mono: none
os:
  - linux
  - osx

before_install:
  - nvm install 10.12.0
  - nvm use 10.12.0

script:
  - dotnet tool restore
  - dotnet paket restore
  - dotnet run --project Build.fsproj -- tests