language: csharp
sudo: required
dist: focal
dotnet: 5.0.100
mono: none

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
      - libunwind8-dev

before_install:
  - nvm install 10.12.0
  - nvm use 10.12.0

script:
  - dotnet tool restore
  - dotnet paket restore
  - dotnet run --project Build.fsproj -- tests